# Generated by Django 4.2.7 on 2023-12-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('z_app', '0003_userprofile_join_date'),
        ('z_app', '0005_alter_tweet_user'),
    ]

    operations = [
    ]
